config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  resources :treinos do
    collection do
      post :adicionar_treino_pronto
      post :copiar_treino
      post :refazer_treino
    end

  end
  resources :treino_prontos
  resources :exercicios, only: [:new, :destroy]


end

app/models/exercicio.rb
class Exercicio < ApplicationRecord
  before_destroy :destroy_codependencias

  belongs_to :treino, optional: true
  belongs_to :treino_pronto, optional: true
  has_many :codependencias, class_name: 'Exercicio', foreign_key: 'codependencia', dependent: :destroy
  belongs_to :exercicio, optional: true
  validates :nome, presence: true

  private

  def destroy_codependencias
    codependencias.each do |codependente|
      codependente.update(codependencia: nil)
      codependente.destroy
    end
  end
end

app/controllers/exercicios_controller.rb
class ExerciciosController < ApplicationController
  before_action :authenticate_user!

  def new
    render turbo_stream: turbo_stream.append(:exercicios, partial: "exercicios/exercicio", locals: { exercicio: Exercicio.new })
  end

  def destroy
    exercicio = Exercicio.find(params[:id])
    exercicio.destroy
  rescue ActiveRecord::RecordNotFound
    exercicio = Exercicio.new(id: params[:id])
  ensure
    render turbo_stream: turbo_stream.remove(exercicio.id)
  end
end

app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

app/views/exercicios/_exercicio.html.erb
<div>
    <%= fields_for "treino[exercicios_attributes][#{turbo_id_for(exercicio)}]", exercicio do |ff| %>
      <fieldset class="mb-4" id="<%= turbo_id_for(exercicio) %>">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">Nível</th>
              <% if @treino.present? && !@treino.id.nil? %>
                <th scope="col">Fazer junto</th>
              <% else %>
                <td></td>
              <% end %>
              <th scope="col">Descrição</th>
              <th scope="col">Concluído</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= ff.text_field :nome, maxlength: 50 %></td>
              <td><%= ff.select :nivel, options_for_select((1..5).to_a, exercicio.nivel) %></td>
              <% if @treino.present? && !@treino.id.nil? %>
                <td><%= ff.collection_select :codependencia, Exercicio.where(treino: @treino).order(:nome), :id, :nome, include_blank: "Nenhuma" %></td>
              <% else %>
                <td></td>
              <% end %>

              <td><%= ff.text_area :descricao, :cols=> 20, :rows => 2, maxlength: 100 %></td>
              <td><%= ff.check_box :concluido %></td>
              <td><%= ff.hidden_field :id %></td>
              <td><%= button_tag formaction: exercicio_path(turbo_id_for(exercicio)), formmethod: :delete, class: "btn btn-danger btn-sm" do %>
                  <i class="fa-regular fa-trash-can"></i>
                <% end %></td>
            </tr>
            </tbody>
          </table>
        </div>
      </fieldset>
    <% end %>
</div>

app/views/exercicios/_form.html.erb
<%= turbo_frame_tag "task_#{form.index}" do %>
  <%= form.hidden_field :id %>
  <div>
    <%= form.label :nome, "Nome do Exercicio", style: "display: block" %><br>
    <%= form.text_field :nome %>
  </div>

  <%= form.submit "destroy exercicio",
                  formaction: exercicio_path(form.index, form.object.id),
                  formmethod: :delete,
                  formnovalidate: true,
                  data: { turbo_frame: "exercicio_#{form.index}" } %>
<% end %>

app/views/exercicios/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/exercicios/edit.html.erb
<h1>Editing exercicio</h1>

<%= render "form", exercicio: @exercicio %>

<br>

<div>
  <%= link_to "Show this exercicio", @exercicio %> |
  <%= link_to "Back to exercicios", exercicios_path %>
</div>

app/views/exercicios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exercicios</h1>

<div id="exercicios">
  <% @exercicios.each do |exercicio| %>
    <%= render exercicio %>
    <p>
      <%= link_to "Show this exercicio", exercicio %>
    </p>
  <% end %>
</div>

<%= link_to "New exercicio", new_exercicio_path %>

app/views/exercicios/new.html.erb
<h1>New exercicio</h1>

<%= render "form", exercicio: @exercicio %>

<br>

<div>
  <%= link_to "Back to exercicios", exercicios_path %>
</div>

app/views/exercicios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercicio %>

<div>
  <%= link_to "Edit this exercicio", edit_exercicio_path(@exercicio) %> |
  <%= link_to "Back to exercicios", exercicios_path %>

  <%= button_to "Destroy this exercicio", @exercicio, method: :delete %>
</div>