config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  resources :treinos do
    collection do
      post :adicionar_treino_pronto
      post :copiar_treino
      post :refazer_treino
    end

  end
  resources :treino_prontos
  resources :exercicios, only: [:new, :destroy]


end

app/models/treino.rb
class Treino < ApplicationRecord

  belongs_to :user
  has_many :exercicios, dependent: :destroy
  accepts_nested_attributes_for :exercicios, allow_destroy: true, reject_if: :all_blank

  validates :nome, presence: true
end

app/controllers/treinos_controller.rb
class TreinosController < ApplicationController
  before_action :set_treino, only: %i[ show edit update destroy copiar_treino refazer_treino]
  before_action :authenticate_user!

  # GET /treinos or /treinos.json
  def index
    @treinos = current_user.treino
  end

  # GET /treinos/1 or /treinos/1.json
  def show
    exercicios_mistos = (1..5).map do |nivel|
      @treino.exercicios.select { |ex| ex[:nivel] == nivel }.shuffle
    end.flatten

    @exercicios = exercicios_mistos.select { |ex| ex[:concluido] == false }.first(5)

    @exercicios_completos = @treino.exercicios
  end

  # GET /treinos/new
  def new
    @treino = current_user.treino.build
    @treino.exercicios.build
  end

  # GET /treinos/1/edit
  def edit
  end

  # POST /treinos or /treinos.json
  def create
    @treino = current_user.treino.build(treino_params)

    respond_to do |format|
      if @treino.save
        format.html { redirect_to treino_url(@treino), notice: "Treino criado com sucesso." }
        format.json { render :show, status: :created, location: @treino }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @treino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treinos/1 or /treinos/1.json
  def update
    respond_to do |format|
      if @treino.update(treino_params)
        format.html { redirect_to treino_url(@treino), notice: "Treino atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @treino }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @treino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treinos/1 or /treinos/1.json
  def destroy
    @treino.destroy

    respond_to do |format|
      format.html { redirect_to treinos_url, notice: "Treino removido com sucesso." }
      format.json { head :no_content }
    end
  end

  def adicionar_treino_pronto

    treino_pronto = TreinoPronto.find(params[:id])

    treino = current_user.treino.build(nome: treino_pronto.nome)

    treino_pronto.exercicios.each do |exercicio|
      treino.exercicios.build(nome: exercicio.nome, concluido: false, nivel: exercicio.nivel,
                              descricao: exercicio.descricao)
    end

    treino.save

    redirect_to treinos_url
  end

  def copiar_treino
    treino_duplicado = @treino.dup
    treino_duplicado.nome = "#{@treino.nome}_(cópia)"
    treino_duplicado.save

    @treino.exercicios.each do |exercicio|
      exercicio_duplicado = exercicio.dup
      exercicio_duplicado.treino_id = treino_duplicado.id
      exercicio_duplicado.codependencia = nil
      exercicio_duplicado.concluido = false
      exercicio_duplicado.save
    end

    redirect_to treinos_url
  end

  def refazer_treino
    @treino.exercicios.each do |exercicio|
      exercicio.concluido = false
      exercicio.save
    end

    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treino
      @treino = Treino.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treino_params
      params.require(:treino).permit(:nome, :user_id, exercicios_attributes: [:id, :nome, :concluido, :nivel, :codependencia, :descricao, :_destroy])
    end
end

app/helpers/treinos_helper.rb
module TreinosHelper
  def associated_tasks_prefix(task)
    new_or_existing = task.new_record? ? "new" : "existing"
    # "project[#{new_or_existing}_task_attributes][]"
    "project[tasks_attributes][]"
  end

end

app/views/treinos/_form.html.erb
<div class="card scrollbar-warning">
  <%= form_with(model: treino, data: { controller: "render-response" }, class: "space-y-4") do |form| %>
    <% if treino.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(treino.errors.count, "error") %> impediu esse treino de ser salvo:</h2>

        <ul>
          <% treino.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="card-header p-3">
        <h5 class="mb-0"><i class="fas fa-tasks me-2"></i><%= @treino.nome %></h5>
      </div>

      <div class="card-body">
        <fieldset>
          <%= form.label :nome, style: "display: block" %>
          <%= form.text_field :nome, maxlength: 50, class: "px-2 py-1 border w-full rounded-md" %>
        </fieldset>

        <div id="exercicios" class="mb-2">
          <%= render @treino.exercicios %>
        </div>

        <div class="mb-2">
          <%= link_to new_exercicio_path, data: { turbo_stream: true }, class: "text-decoration-none link-dark" do %>
            Adicionar exercício <i class="fa-solid fa-plus"></i>
          <% end %>
        </div>

          <% if form.object.persisted? %>
            <%= form.submit "Atualizar", class: "btn btn-dark" %>
          <% else %>
            <%= form.submit "Criar", class: "btn btn-dark" %>
          <% end %>
      </div>
  <% end %>

</div>

app/views/treinos/_treino.html.erb
<div class="card">
  <div id="<%= dom_id treino %>">

    <div class="card-header p-3">
      <h1><%= @treino.nome.titleize %></h1>
    </div>

    <div class="card-body">

        <% if @exercicios.present? %>
          <%= form_with(model: @treino, local: true) do |form| %>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
              <tr>
                <th scope="col">Exercício</th>
                <th scope="col">Nível</th>
                <th scope="col">Descrição</th>
                <th scope="col">Fazer junto</th>
                <th scope="col">Concluído</th>
              </tr>
              </thead>

              <tbody>
              <% @exercicios.each do |exercicio| %>
                <%= form.fields_for :exercicios, exercicio do |exercicio_fields| %>
                  <tr>
                    <td><%= exercicio_fields.label :nome, exercicio.nome %></td>
                    <td><%= exercicio_fields.label :nivel, exercicio.nivel %></td>

                    <% if exercicio.descricao.present? %>
                      <td style="word-break: break-word; white-space: normal;"><%= exercicio_fields.label :descricao, exercicio.descricao %></td>
                    <% else %>
                      <td></td>
                    <% end %>

                    <% if exercicio.codependencia.present? %>
                      <td><%= @exercicios_completos.find{|e| e.id == exercicio.codependencia }.nome %></td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <td><%= exercicio_fields.check_box :concluido %></td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
            <%= form.submit "Salvar", class: "btn btn-dark"%>
          <% end %>
        <% else %>
          <p> Todos os exercícios foram concluidos! </p>
          <p>
            <%= button_to "Refazer", refazer_treino_treinos_path(id: treino.id), method: :post, class: "btn btn-dark btn-sm" %>
          </p>
        <% end %>

    </div>

  </div>
</div>

app/views/treinos/edit.html.erb
<section class="min-vh-100" style="background-color: #1e1e1e;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="text-3xl text-center text-white">

          <%= render "form", treino: @treino %>

            <%= link_to "Mostrar esse treino", @treino, class: "text-decoration-none link-light" %> |
            <%= link_to "Voltar para treinos", treinos_path, class: "text-decoration-none link-light" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/treinos/index.html.erb
<section class="min-vh-100" style="background-color: #1e1e1e;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="text-3xl text-center">
          <p style="color: green"><%= notice if notice%></p>
          <p style="color: green"><%= alert if alert%></p>
          <div class="card">

            <div class="card-header p-3" >
              <h5 class="mb-0"><i class="fas fa-tasks me-2"></i>Treinos</h5>
            </div>

            <div class="card-body">
                <table class="table table-hover">
                  <tbody>
                    <% @treinos.each do |treino| %>
                      <tr>
                        <% if treino.exercicios.all? { |ex| ex.concluido } %>
                          <td><%= link_to "#{treino.nome.titleize} (Concluído)", treino, class: "text-decoration-none link-dark link-opacity-50-hover" %></td>
                        <% else %>
                          <td><%= link_to "#{treino.nome.titleize}", treino, class: "text-decoration-none link-dark link-opacity-50-hover" %></td>
                        <% end %>
                        <td class="text-end">
                          <div class="d-flex justify-content-end">
                            <%= button_to "Copiar", copiar_treino_treinos_path(id: treino.id), method: :post, class: "btn btn-dark btn-sm me-2" %>
                            <%= button_to treino, method: :delete, form: { data: { turbo_confirm: 'Tem certeza?' } }, class: "btn btn-danger btn-sm" do %>
                              <i class="fa-regular fa-trash-can"></i>
                            <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= button_to "Novo treino", new_treino_path, method: :get, class: "btn btn-dark" %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/treinos/new.html.erb
<section class="min-vh-100" style="background-color: #1e1e1e;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="text-3xl text-center text-white">
          <h1>Novo Treino</h1>

          <%= render "form", treino: @treino %>

          <%= link_to "Voltar para treinos", treinos_path, class: "text-decoration-none link-light" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/treinos/show.html.erb
<section class="min-vh-100" style="background-color: #1e1e1e;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="text-3xl text-center">
          <p style="color: green"><%= notice if notice%></p>
          <p style="color: green"><%= alert if alert%></p>
            <%= render @treino %>

            <div>
              <%= link_to "Editar esse treino", edit_treino_path(@treino), class: "text-decoration-none link-light" %> |
              <%= link_to "Voltar para treinos", treinos_path, class: "text-decoration-none link-light" %>

              <%= button_to "Apagar treino", @treino, method: :delete, form: { data: { turbo_confirm: 'Tem certeza?' } }, class: "btn btn-danger" %>
            </div>

        </div>
      </div>
    </div>
  </div>
</section>