config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  resources :treinos do
    collection do
      post :adicionar_treino_pronto
      post :copiar_treino
      post :refazer_treino
    end

  end
  resources :treino_prontos
  resources :exercicios, only: [:new, :destroy]


end

app/models/treino_pronto.rb
class TreinoPronto < ApplicationRecord

  has_many :exercicios, dependent: :destroy
  validates :nome, presence: true

end

app/controllers/treino_prontos_controller.rb
class TreinoProntosController < ApplicationController
  before_action :set_treino_pronto, only: %i[ show edit update destroy ]

  # GET /treino_prontos or /treino_prontos.json
  def index
    @treino_prontos = TreinoPronto.all
  end

  # GET /treino_prontos/1 or /treino_prontos/1.json
  def show

    @exercicios = @treino_pronto.exercicios
  end

  # GET /treino_prontos/new
  def new
    @treino_pronto = TreinoPronto.new
  end

  # GET /treino_prontos/1/edit
  def edit
  end

  # POST /treino_prontos or /treino_prontos.json
  def create
    @treino_pronto = TreinoPronto.new(treino_pronto_params)

    respond_to do |format|
      if @treino_pronto.save
        format.html { redirect_to treino_pronto_url(@treino_pronto), notice: "treino pronto was successfully created." }
        format.json { render :show, status: :created, location: @treino_pronto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @treino_pronto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treino_prontos/1 or /treino_prontos/1.json
  def update
    respond_to do |format|
      if @treino_pronto.update(treino_pronto_params)
        format.html { redirect_to treino_pronto_url(@treino_pronto), notice: "treino pronto was successfully updated." }
        format.json { render :show, status: :ok, location: @treino_pronto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @treino_pronto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treino_prontos/1 or /treino_prontos/1.json
  def destroy
    @treino_pronto.destroy

    respond_to do |format|
      format.html { redirect_to treino_prontos_url, notice: "treino pronto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treino_pronto
      @treino_pronto = TreinoPronto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treino_pronto_params
      params.fetch(:treino_pronto, {})
    end
end

app/views/treino_prontos/_form.html.erb
<%= form_with(model: treinos_pronto) do |form| %>
  <% if treinos_pronto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(treinos_pronto.errors.count, "error") %> prohibited this treinos_pronto from being saved:</h2>

      <ul>
        <% treinos_pronto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/treino_prontos/_treino_pronto.html.erb
<div class="card">
  <div id="<%= dom_id treino_pronto %>">
    <div class="card-header p-3">
      <h1><%= @treino_pronto.nome.titleize %></h1>
    </div>

    <div class="card-body">
      <table class="table table-hover">
        <thead>
        <tr>
          <th scope="col">Exercício</th>
          <th scope="col">Dificuldade</th>
          <th scope="col">Descrição</th>
        </tr>
        </thead>
        <tbody>
          <% @exercicios.each do |exercicio| %>
            <tr>
              <td><%= exercicio.nome %></td>
              <td>Nível: <%= exercicio.nivel %></td>
              <td><%= exercicio.descricao %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= button_to "Adicionar treino", adicionar_treino_pronto_treinos_path(id: @treino_pronto.id), method: :post, class: "btn btn-dark" %>

    </div>
  </div>
</div>

app/views/treino_prontos/edit.html.erb
<h1>Editing treinos pronto</h1>

<%= render "form", treinos_pronto: @treinos_pronto %>

<br>

<div>
  <%= link_to "Show this treinos pronto", @treinos_pronto %> |
  <%= link_to "Back to treinos prontos", treinos_prontos_path %>
</div>

app/views/treino_prontos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Treinos prontos</h1>

<div id="treinos_prontos">
  <% @treinos_prontos.each do |treinos_pronto| %>
    <%= render treinos_pronto %>
    <p>
      <%= link_to "Show this treinos pronto", treinos_pronto %>
    </p>
  <% end %>
</div>

<%= link_to "New treinos pronto", new_treinos_pronto_path %>

app/views/treino_prontos/new.html.erb
<h1>New treinos pronto</h1>

<%= render "form", treinos_pronto: @treinos_pronto %>

<br>

<div>
  <%= link_to "Back to treinos prontos", treinos_prontos_path %>
</div>

app/views/treino_prontos/show.html.erb
<section class="min-vh-100" style="background-color: #1e1e1e;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="text-3xl text-center">

          <%= render @treino_pronto %>

        </div>
      </div>
    </div>
  </div>
</section>